[package]
name = "jyrki"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
simple_logger = "5"
tokio = { version = "1", features = ["full"] }
reqwest = "0.12"
serde = "1"
serde_json = "1"
anyhow = "1"
wgui = { git = "https://github.com/J45k4/wgui.git", rev = "c851abb0b2123e1adc6e5fa31fb78099184dad73" }
